# Generated by Django 2.1.1 on 2018-12-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181208_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advID', models.IntegerField(primary_key=True, serialize=False)),
                ('advStartDate', models.DateField()),
                ('advEndDate', models.DateField()),
                ('advDescription', models.CharField(max_length=200)),
                ('advProp', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
